# Site settings
title: Robotic Lacing
subtitle: Lace in Space
email: ldreier@princeton.edu
description: Lace in Space presents the outcome of an interdisciplinary investigation into new, spatial possibilities for bobbin lace, a centuries-old textile art. 
baseurl: "/robotic_lacing"
url: createchaos.github.io
author: Lauren Dreier
street_address: Labatut Pavillion, Princeton University
city: Princeton
state: NJ
zip_code: 08540
country: USA

# Homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# Build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
